name: Build, Push & Pull MERN Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker login using secrets
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t ayush01123/mern-app:latest .

      # Push image to Docker Hub
      - name: Push Docker Image
        run: docker push ayush01123/mern-app:latest

      # Pull & run image
      - name: Pull & Run Docker Image
        run: |
          docker pull ayush01123/mern-app:latest
          docker run -d -p 3000:3000 ayush01123/mern-app:latest
